#!/usr/bin/env bash

echo "Running pre-commit hook"
python3 tests/test_validate_markdown.py && python3 tests/test_selenium.py

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Tests must pass before commit!"
 exit 1
fi